config/routes.rb
Boxtagram::Application.routes.draw do
  resources :users

  match ':controller/:action'

  root :to => 'static#home'

end

app/models/insta_crawl.rb
require 'resque/plugins/heroku'

class InstaCrawl
  @queue = :crawl
  extend Resque::Plugins::Heroku

  def self.perform(user_id)
    user = User.find(user_id)
    ig = Instagramr.new(user.instagram_access_token)
    db_client = Dropbox::API::Client.new(token: user.dropbox_access_token, secret: user.dropbox_secret_token)
    next_url = ig.feed_root
    pcnt = 0
    while next_url do
      pcnt = pcnt + 1
      puts "Page #{pcnt}"
      page = ig.feed(next_url)
      next_url = page["pagination"]["next_url"]
      page["data"].each do |picture|
        url = picture["images"]["standard_resolution"]["url"]
        filename = url.split('/').last
        puts "\t\tgetting: #{filename}: #{url}"

        db_exists = db_client.search(filename)
        begin
          if db_exists.blank?
            #  queue get picture
            Resque.enqueue(InstaFetch, user.id, filename, url)
          else
            puts "already got it"
          end
        rescue Exception => e
          puts e.message
          redo if e.message.include?('reset')
        end
      end
    end
    # send email
    CrawlerMailer.crawl_complete_email(user).deliver
  end
end

app/models/insta_fetch.rb
require 'resque/plugins/heroku'

class InstaFetch
  @queue = :fetch
  extend Resque::Plugins::Heroku

  def self.perform(user_id,filename,url)
    user = User.find(user_id)
    db_client = Dropbox::API::Client.new(token: user.dropbox_access_token, secret: user.dropbox_secret_token)
    puts "getting #{url}"
    db_client.upload(filename,Net::HTTP.get(URI.parse(url)))
  end
end

app/models/instagramr.rb
class Instagramr
  include HTTParty
  attr_accessor :token, :access_token

  def feed_root
    "https://api.instagram.com/v1/users/self/media/recent/"
  end

  def initialize(access_token)
    @access_token = access_token
  end

  def feed(url)
    the_url = "#{url}?access_token=#{self.access_token}"
    self.class.get(the_url)
  end

  def profile_picture
    url = "https://api.instagram.com/v1/users/self/?access_token=#{self.token}"
    response = Hashie::Mash.new(HTTParty.get(url))
    response["data"]["profile_picture"]
  end

  def profile
    url = "https://api.instagram.com/v1/users/self/?access_token=${{INSTAGRAM_API_ACCESS_TOKEN}}"
    response = HTTParty.get(url).parsed_response['data']
    response["instagram_id"] = response.delete('id')
    response.delete('bio')
    response
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :instagram_id, :instagram_access_token, :username, :full_name, :profile_picture, :email
  validates_email_format_of :email, :allow_blank => true
  after_save :queue_crawl

  private
  
  def queue_crawl
    if self.instagram_id.present? &&
        self.instagram_access_token.present? &&
        self.dropbox_access_token.present? &&
        self.dropbox_secret_token.present? &&
        self.email.present? &&
        self.has_migrated == false
      Resque.enqueue(InstaCrawl, self.id)
    end
  end
end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController

  def connect_to_instagram
    redirect_to Instagram.authorize_url(:redirect_uri => Settings.instagram.callback)
  end

  def instagram
    response = Instagram.get_access_token(params[:code], :redirect_uri => Settings.instagram.callback)
    session[:instagram_access_token] = response.access_token
    instagramr = Instagramr.new(session[:instagram_access_token])
    profile = instagramr.profile
    session[:instagram_id] = profile["instagram_id"]

    u = User.find_or_create_by_instagram_id(instagram_id: profile["instagram_id"].to_i,
        username: profile["username"], 
        full_name: profile["full_name"], profile_picture: profile["profile_picture"])

    u.instagram_access_token = session[:instagram_access_token]
    u.dropbox_access_token = session[:dropbox_access_token] if session[:dropbox_access_token].present?
    u.dropbox_secret_token = session[:dropbox_secret_token] if session[:dropbox_secret_token].present?
    u.save
    redirect_to root_url
  end

  def connect_to_dropbox
    consumer = Dropbox::API::OAuth.consumer(:authorize)
    session[:dropbox_request_token] = consumer.get_request_token
    redirect_to session[:dropbox_request_token].authorize_url(oauth_callback: Settings.dropbox.callback)
  end

  def dropbox
    res = session[:dropbox_request_token].get_access_token(oauth_verifier: params[:oauth_token])

    # client = Dropbox::API::Client.new token: res.token, secret: res.secret
    session[:dropbox_access_token] = res.token
    session[:dropbox_secret_token] = res.secret

    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @instagram = Instagramr.new(session[:instagram_access_token])
    if session[:dropbox_access_token] && session[:dropbox_secret_token]
      @db_client = Dropbox::API::Client.new(token: session[:dropbox_access_token], secret: session[:dropbox_secret_token])
    end
    @user = User.find_by_instagram_id(session[:instagram_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## GET /users
  ## GET /users.json
  #def index
  #  @users = User.all
  #
  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @users }
  #  end
  #end
  #
  ## GET /users/1
  ## GET /users/1.json
  #def show
  #  @user = User.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @user }
  #  end
  #end
  #
  ## GET /users/new
  ## GET /users/new.json
  #def new
  #  @user = User.new
  #
  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @user }
  #  end
  #end
  #
  ## GET /users/1/edit
  #def edit
  #  @user = User.find(params[:id])
  #end

  # POST /users
  # POST /users.json
  #def create
  #  @user = User.new(params[:user])
  #
  #  respond_to do |format|
  #    if @user.save
  #      format.html { redirect_to @user, notice: 'User was successfully created.' }
  #      format.json { render json: @user, status: :created, location: @user }
  #    else
  #      format.html { render action: "new" }
  #      format.json { render json: @user.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to root_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_url, alert: @user.errors.full_messages }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  #def destroy
  #  @user = User.find(params[:id])
  #  @user.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to users_url }
  #    format.json { head :no_content }
  #  end
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper  
  def bootstrap_flash
   flash_messages = []
   flash.each do |type, message|
     type = :success if type == :notice
     type = :error   if type == :alert
     text = content_tag(:div, link_to("x", "#", :class => "close", "data-dismiss" => "alert") + message, :class => "alert fade in alert-#{type}")
     flash_messages << text if message
   end
   flash_messages.join("\n").html_safe
 end
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/crawler/crawl_complete_email.html.haml
%p Thanks for using #{Settings.company_name}

%p Your images have been added to the queue for fetching. You should start to see them in your Dropbox folder.

=image_tag('finder.png')

%p Thanks, Boxtagram

=link_to('@boxtagramapp','https://twitter.com/boxtagramapp')

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta{:content => "article", :property => "og:type"}/
    %meta{:content => "Boxtagram", :property => "og:title"}/
    %meta{:content => "http://www.boxtagram.com/", :property => "og:url"}/
    %meta{:content => "Boxtagram", :property => "og:site_name"}/
    %meta{:content => "http://www.boxtagram.com/images/pictures.png", :property => "og:image"}/
    %meta{:content => "Backup your Instagram pictures to your Dropbox. Cuz your stuff is your stuff.", :property => "og:description"}/

    %title= content_for?(:title) ? yield(:title) : Settings.app_name
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/images/favicon.ico" rel="shortcut icon")
    %link(href='http://fonts.googleapis.com/css?family=Gafata' rel='stylesheet' type='text/css')
    :css
      html,
      body {
        height: 100%;
        /* The html and body elements cannot have any padding or margin. */
      }
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by it's height */
        margin: 0 auto -60px;
      }
      #push,
      #footer {
        height: 60px;
      }
      #footer {
        background-color: #f5f5f5;
      }
      h1{
          font-family: 'Gafata', sans-serif;
          font-weight: 400;
          font-size: 30px;
      }
      h2{
          font-family: 'Gafata', sans-serif;
          font-weight: 400;
          font-size: 25px;
      }
      h3{
          font-family: 'Gafata', sans-serif;
          font-weight: 300;
          font-size: 20px;
      }
      a:visited {
          color:#fff;
      }
      a#tweet-me, a#tweet-me:hover{
        background-color:#fff;
        color:#999;
        text-decoration:none;
      }

  %body
    #wrap
      .navbar.navbar-top
        .navbar-inner
          .container
            / %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            /   %span.icon-bar
            /   %span.icon-bar
            /   %span.icon-bar
            %a.brand(href="#") #{Settings.app_name} ß
      .container
        - if bootstrap_flash.present?
          .row
            .span12
              = bootstrap_flash
        = yield
        .row
          .span12.ad
            :javascript
              google_ad_client = "ca-pub-9938589600905527";
              /* Boxtagram */
              google_ad_slot = "3593602457";
              google_ad_width = 728;
              google_ad_height = 90;  
            %script{:src => "http://pagead2.googlesyndication.com/pagead/show_ads.js", :type => "text/javascript"}
        #push
    %footer.navbar.navbar-inner
      .container
        %p.muted &copy; #{Settings.app_name} 2012 Made with you in mind... #{link_to('@tjhanley','https://www.twitter.com/tjhanley',class: 'muted')}
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37327773-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path